name: Estimate infra cost
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  infra-cost:
    runs-on: ubuntu-latest
    name: Show Infracost diff
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: path/to/code

      - name: 'Terraform plan'
        id: plan
        run: terraform plan -out plan.tfplan
        working-directory: path/to/code

      - name: 'Terraform show'
        id: show
        run: terraform show -json plan.tfplan
        working-directory: path/to/code

      - name: 'Save Plan JSON'
        run: echo '${{ steps.show.outputs.stdout }}' > plan.json # Do not change

      - name: Run infracost diff
        uses: infracost/infracost-gh-action@master # Use a specific version instead of master if locking is preferred
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: plan.json # Do not change as this file is generated above
